version: "3.8"
services:
  semanticServices:
    build: .
    command: python apis/http/api/endpoints.py
    image: jperdek/semantic-aspects-services
    ports:
      - "5000:5000"
    extra_hosts:
        - "hostname1  localhost:127.0.0.1"
    container_name: semanticServices
    environment:
      FLASK_ENV: development
    networks:
      - buildernet
    env_file:
       - 'variables.env'
  semanticFrontend:
    build:
      context: ./frontend/semanticAspects
      dockerfile: Dockerfile
    image: jperdek/semantic-aspects-frontend
    ports:
      - "4200:80"
    container_name: semanticAspects
    environment:
      ANGULAR_ENV: development
    networks:
      - buildernet
  cooccurrenceNetwork: 
    build:
       context: ./neo4j/co-occurrence-network
       dockerfile: Dockerfile
    image: jperdek/co-occurrence-network
    hostname: neo4j_co_occurrence
    container_name: neo4j_co_occurrence
    ports:
      - "7475:7475"
      - "7688:7688"
    volumes:
      - ./neo4j/plugins:/plugins
    environment:
      NEO4J_AUTH: neo4j/neo4j1
      NEO4J_dbms_logs_debug_level: DEBUG
  semanticBaseYago: 
    build:
       context: ./neo4j/semantic-base-yago
       dockerfile: Dockerfile
    image: jperdek/semantic_base_yago
    hostname: neo4j_yago
    container_name: neo4j_yago
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/plugins:/plugins
    environment:
      NEO4J_AUTH: neo4j/perdekj
      NEO4J_dbms_logs_debug_level: DEBUG
networks:
  buildernet:
    driver: "bridge"
    