version: "3.8"
services:
  cooccurrenceNetwork: 
    build:
       context: ./neo4j
       dockerfile: Dockerfile
    image: jperdek/co-occurrence-network
    hostname: neo4j
    container_name: neo4j
    ports:
      - "7475:7475"
      - "7688:7688"
    volumes:
      - ./neo4j/plugins:/plugins
    environment:
      NEO4J_AUTH: neo4j/neo4j1
      NEO4J_dbms_logs_debug_level: DEBUG
networks:
  buildernet:
    driver: "bridge"
    